apiVersion: v1
kind: Service
metadata:
  name: gradle-webapp
  namespace: testbed
spec:
  ports:
    - name: "8080"
      port: 8082
      targetPort: 8080
  selector:
    app: gradle-webapp
  type: NodePort